#preload=$HOME/Pictures/wallpapers/nerv/nerv1.jpg
#wallpaper=DP-1,$HOME/Pictures/wallpapers/nerv/nerv1.jpg 
wallpaper {
    monitor = DP-1
    path = $HOME/Pictures/wallpapers/nerv/
    fit_mode = cover
    timeout = 60 
}
